language: go
dist: trusty
sudo: false

go:
  - "1.9.X"
  - "1.10.X"
  - "1.11.X"
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/mitchellh/gox
  - go get honnef.co/go/tools/...
  - go get -t .

script:
  - go test -v
  - gox -os="linux windows freebsd openbsd"
  - diff <(goimports -d *.go) <(printf "")
  - diff <(unused .) <(printf "")
  - diff <(gosimple .) <(printf "")
  - diff <(staticcheck .) <(printf "")

after_success:
  - diff <(golint ./...) <(printf "")
